sudo: required
dist: trusty
language: node_js
node_js:
  - '6'
branches:
   only:
      - master
before_script:
   - npm install -g @angular/cli
script:
   - ng build --prod
env:
  global:
    - "FTP_USER=bigbossduck@bigbossduck.com"
    - "FTP_PASSWORD=S3cur1ty"
after_success:
    "find dist -type f -exec curl -u bigbossduck@bigbossduck.com:Colombia2016 --ftp-create-dirs -T {} ftp://ftp.conectanddo.com/{} \;"